name: Deploy to VPS

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Setup VPS
    - name: Setup VPS
      env:
        PAT: ${{ secrets.PAT }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 600 ssh_key
        ssh -i ssh_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
        
        # Install NVM
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
  
        # Set up NVM environment
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # Load nvm
  
        # Install Node.js and npm
        nvm install node
        nvm use node
        npm install -g npm
        npm i -g ts-node
        npm install pm2 -g
        export PATH=$PATH:./node_modules/.bin
        pm2 -v
        rm -rf "/root/repo"
        EOF

    # Step 3: Setup ENVs
    - name: Setup ENVs
      env:
        PAT: ${{ secrets.PAT }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL}}
        MS_BLURTY_ADMIN_APIKEY: ${{ secrets.MS_BLURTY_ADMIN_APIKEY}}
        MS_BLURTY_CLIENT_APIKEY: ${{ secrets.MS_BLURTY_CLIENT_APIKEY}}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 600 ssh_key
        ssh -i ssh_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
        
        # Setup environmental variables
        echo "DATABASE_URL=${{ secrets.DATABASE_URL}}" | sudo tee -a /etc/environment
        echo "MS_BLURTY_ADMIN_APIKEY=${{ secrets.MS_BLURTY_ADMIN_APIKEY}}" | sudo tee -a /etc/environment
        echo "MS_BLURTY_CLIENT_APIKEY=${{ secrets.MS_BLURTY_CLIENT_APIKEY}}" | sudo tee -a /etc/environment

        source /etc/environment
        EOF

    # Step 4: Deploy to VPS
    - name: Deploy to VPS
      env:
        PAT: ${{ secrets.PAT }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 600 ssh_key
        ssh -i ssh_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
        # Define project directory
        PROJECT_DIR="/root/repo"

        # Load nvm environment
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

        # Check if project directory exists
        if [ ! -d "$PROJECT_DIR" ]; then
          echo "Directory $PROJECT_DIR does not exist. Cloning repository..."
          git clone https://$PAT@github.com/HagerPrograms/ms-blurty.git $PROJECT_DIR
        else
          echo "Directory $PROJECT_DIR exists. Pulling latest changes..."
          cd $PROJECT_DIR
          git pull origin main
        fi

        # Navigate to project directory

        cd $PROJECT_DIR 
        echo $PROJECT_DIR

        # Install Node.js via nvm
        nvm install
        nvm use
 
        # Install production dependencies
        npm install --omit-dev
        npm run build
        pm2 stop app
        pm2 start app.js
        pm2 save
        pm2 startup
        exit 0
        EOF
        
