name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup and Deploy to VPS
        env:
          PAT: ${{ secrets.PAT }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MS_BLURTY_ADMIN_APIKEY: ${{ secrets.MS_BLURTY_ADMIN_APIKEY }}
          MS_BLURTY_CLIENT_APIKEY: ${{ secrets.MS_BLURTY_CLIENT_APIKEY }}
        run: |
          set -e
          trap 'echo "[ERROR] Deployment script failed on GitHub runner"; exit 1' ERR
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key

          ssh -i ssh_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
          set -e
          trap 'echo "[ERROR] Deployment failed inside SSH session at line \$LINENO"; exit 1' ERR
          echo "[INFO] Starting deployment on VPS..."

          # Setup NVM and Node
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] || curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

          echo "[INFO] Installing Node.js..."
          nvm install 18.18.0
          nvm use 18.18.0

          echo "[INFO] Installing global tools..."
          npm install -g pm2
          pm2 -v

          echo "[INFO] Setting environment variables..."
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" | sudo tee /etc/environment
          echo "MS_BLURTY_ADMIN_APIKEY=${{ secrets.MS_BLURTY_ADMIN_APIKEY }}" | sudo tee -a /etc/environment
          echo "MS_BLURTY_CLIENT_APIKEY=${{ secrets.MS_BLURTY_CLIENT_APIKEY }}" | sudo tee -a /etc/environment
          source /etc/environment

          PROJECT_DIR="/root/repo"

          echo "[INFO] Cloning or updating repository..."
          if [ ! -d "$PROJECT_DIR" ]; then
            git clone https://$PAT@github.com/HagerPrograms/ms-blurty.git $PROJECT_DIR
          else
            cd $PROJECT_DIR
            git pull origin main
          fi

          cd $PROJECT_DIR

          echo "[INFO] Installing dependencies and building project..."
          npm install --omit=dev
          npm run build

          echo "[INFO] Restarting app with PM2..."
          pm2 reload app || pm2 start app
          pm2 save
          pm2 startup

          echo "[INFO] Deployment completed successfully."
          EOF

      - name: Clean up SSH key
        run: rm -f ssh_key
